name: Relics
main: net.williserver.relics.RelicsPlugin
version: 1.0
api-version: 1.21
softdepend:
  - VeinMiner

commands:
  relics:
    description: Base command for interfacing with Relics plugin
    usage: "Use /relics help for usage information."