name: Relics
main: net.williserver.relics.RelicsPlugin
version: 1.0
api-version: 1.21
softdepend:
  - VeinMiner

commands:
  relics:
    description: Base command for interfacing with Relics plugin
    usage: "Use /relics help for usage information."

permissions:
  relics.deregister:
    description: Allows /relics deregister
    default: op
  relics.register:
    description: Allows /relics register
    default: op
  relics.claim:
    description: Allows /relics claim
    default: true
  relics.list:
    description: Allows /relics list
    default: true
  relics.help:
    description: Allows /relics help
    default: true